#!/usr/bin/env bash
# vim: set ft=sh :

if [ "$1" == "--md" ]; then
  markdown_link="$2"
  title="$(echo "$markdown_link" | sed 's/^\[//' | sed 's/].*$//')"
  body="Source: $markdown_link"
else
  title="$1"
  body="$2"
fi

date="$(date +'%Y-%m-%d')"
safe_filename_title="$(echo "$title" | sed 's/[^A-Za-z0-9 ]//g' | sed 's/ /-/g')"
path="_posts/$date-$safe_filename_title.md"

cat <<EOF > "$path"
---
layout: post
title:  "$title"
date:   $date
---

$body
EOF

$EDITOR "$path"
git add "$path"
git ci -m "Add $path"
