#!/bin/bash

path="$1"

sed -i.bak 's/<pre><code class="language-ruby">/```ruby\n/' "$path"
sed -i.bak 's/<\/code><\/pre>/```/' "$path"
sed -i.bak 's/&lt;/</g' "$path"
sed -i.bak 's/&gt;/>/g' "$path"
sed -i.bak "s/\r//" "$path"

rm "$path.bak"
